version: '3.7'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
#      - discovery.seed_hosts=es02,es03
#      - cluster.initial_master_nodes=es01
# disabled swap so ignore the following param
# also problems setting the ulimits for memlock, could not make memlock work, despite 
# numerous articles read and solutions tried
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    volumes:
      - type: bind
        source: /mnt/swarm-shared/joncatlin-development/shared-volumes/elastic-vol1
        target: /usr/share/elasticsearch/data
    # ports:
    #   - 9200:9200
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    ports:
      - 5601:5601
    networks:
      - elastic
    environment:
#      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: http://es01:9200/
    depends_on: 
      - es01

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.1.1
    # https://github.com/docker/swarmkit/issues/1951
    hostname: "{{.Node.Hostname}}-filebeat"
    # Need to override user so we can access the log files, and docker.sock
    user: root
    networks:
      - elastic
#    configs:
#      - source: fb_config
#        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - type: bind
        source: /mnt/swarm-shared/joncatlin-development/shared-volumes/filebeat-vol1
        target: /usr/share/filebeat/data
      # mount the config
      - type: bind
        source: /mnt/swarm-shared/joncatlin-development/shared-volumes/filebeat-config/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml:ro

      # This is needed for filebeat to load container log path as specified in filebeat.yml
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro

      # # This is needed for filebeat to load jenkins build log path as specified in filebeat.yml
      # - /var/lib/docker/volumes/jenkins_home/_data/jobs/:/var/lib/docker/volumes/jenkins_home/_data/jobs/:ro

      # This is needed for filebeat to load logs for system and auth modules
#      - /var/log/:/var/log/:ro
      # This is needed for filebeat to load logs for auditd module
      # - /var/log/audit/:/var/log/audit/:ro
    environment:
      - ELASTICSEARCH_HOST=es01
      - KIBANA_HOST=kibana
#      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
#      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    # disable strict permission checks
    command: 
      - "-e"
      - "--strict.perms=false"
    deploy:
      mode: global


  # es02:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
  #   container_name: es02
  #   environment:
  #     - node.name=es02
  #     - cluster.name=es-docker-cluster
  #     - discovery.seed_hosts=es01,es03
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data02:/usr/share/elasticsearch/data
  #   networks:
  #     - elastic
  # es03:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
  #   container_name: es03
  #   environment:
  #     - node.name=es03
  #     - cluster.name=es-docker-cluster
  #     - discovery.seed_hosts=es01,es02
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data03:/usr/share/elasticsearch/data
  #   networks:
  #     - elastic

networks:
  elastic:
